### ISSUE TITLE
Not loading, dns not found

### ISSUE THREAD

**Issue by hawkman83** [hxim/TwemojiPlugin#1]
Emoji's not loading in menu.  

browser console shows this error: 

GET https://twemoji.maxcdn.com/v/latest/twemoji.min.js net::ERR_NAME_NOT_RESOLVED

**Comment by hxim** [comment]
Because MaxCDN CDN is no longer working I switched URL from "twemoji.maxcdn.com" to "cdn.jsdelivr.net" and it should be working now.
